import Node from './Node';
import editForm from './Tree.form';
declare const NestedDataComponent: any;
export default class TreeComponent extends NestedDataComponent {
    static editForm: typeof editForm;
    static schema(...extend: any[]): any;
    static get builderInfo(): {
        title: string;
        icon: string;
        weight: number;
        documentation: string;
        showPreview: boolean;
        schema: any;
    };
    constructor(...args: any[]);
    get emptyValue(): {};
    get viewComponents(): any;
    init(): any;
    get disabled(): any;
    set disabled(disabled: any);
    get isDefaultValueComponent(): boolean;
    destroy(): void;
    createComponents(data: any, node?: any): any;
    removeComponents(components: any): any;
    render(): any;
    renderTree(node: Node, odd?: boolean): any;
    renderChildNodes(nodes: any[], odd: any): any;
    renderEdit(node: Node): any;
    renderView(node: Node): any;
    attach(element: any): any;
    attachNode(element: any, node: any): any;
    attachActions(node: any): void;
    attachComponents(node: any, ...args: any[]): any;
    attachChildren(node: any): any;
    setValue(value: any, flags?: {}): any;
    addChild(parent: any): void;
    cancelNode(node: any): void;
    editNode(node: any): void;
    removeNode(node: any): void;
    revertNode(node: any): void;
    saveNode(node: any): void;
    toggleNode(node: any): void;
    removeRoot(): void;
    setRoot(): void;
    getValue(): any;
    updateTree(): void;
    checkData(data: any, flags: any, row: any): any;
    checkNode(data: any, node: any, flags?: any, row?: any): any;
    getComponents(): any;
    getValueAsString(value: any, options: any): any;
}
export {};
